davidB/tracing-opentelemetry-instrumentation-sdk

- Cargo.toml
- src/middleware.rs
I also had to use a `str` instead of `SpanKind` because its Display impl was removed. I checked on tracing-opentelemetry and they did the same.
I suppose we need to go to `0.5` to release it?
> update opentelemetry dependencies to the latest version

- src/middleware.rs
According to https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md
```
[1]: 'http.route' MUST NOT be populated when this is not supported by the HTTP server framework 
as the route attribute should have low-cardinality and the URI path can NOT substitute it.
```
> fix: do not populate http.route when not supported by the HTTP server

- Cargo.toml
- src/middleware.rs
Currently extracting the route path silently fails with axum 0.6 RC. With this change, the path is available.
I'm not sure of the timeframe for the 0.6 release; I would like to hope it would be available soon, but https://github.com/tokio-rs/axum/issues/1416 makes me think it may take a bit more time.
> Compile with axum 0.6.0-rc.2

- src/tools/mod.rs
If only the `tracer` feature is enabled, then the library fails to compile, with missing symbols `sdktrace`, `TraceError` and `Resource`.
This change makes those imports available for this configuration.
> Fix compile error with only `tracer` feature configured.

- src/middleware/trace_extractor.rs
fallback to req uri path for nested route (we can not get matched router in nested router handler)
otherwise our span name will be strange.
this is a known issue for Axum: https://github.com/tokio-rs/axum/issues/1441
this PR is a workaround.
> fix: fallback to req uri path for nested route 

- axum-tracing-opentelemetry/Cargo.toml
Make it explicit that rust 1.70 is required
On older versions we might have this kind of compile error.
```
error: implementation of `std::fmt::Debug` is not general enough                                                                                                                                                                                                                                                                                                                         
--> axum-tracing-opentelemetry/src/middleware/trace_extractor.rs:68:5 …
```
> axum-tracing-opentelemetry requires, at least, rust 1.70 to compile.

- testing-tracing-opentelemetry/src/snapshots/testing_tracing_opentelemetry__call_with_w3c_trace.snap
- testing-tracing-opentelemetry/src/snapshots/testing_tracing_opentelemetry__call_with_w3c_trace_otel_spans.snap
- testing-tracing-opentelemetry/src/snapshots/testing_tracing_opentelemetry__empty_http_route_for_nonexisting_route.snap
- testing-tracing-opentelemetry/src/snapshots/testing_tracing_opentelemetry__empty_http_route_for_nonexisting_route_otel_spans.snap
- testing-tracing-opentelemetry/src/snapshots/testing_tracing_opentelemetry__extract_route_from_nested.snap
- testing-tracing-opentelemetry/src/snapshots/testing_tracing_opentelemetry__extract_route_from_nested_otel_spans.snap
- testing-tracing-opentelemetry/src/snapshots/testing_tracing_opentelemetry__filled_http_headers.snap
- testing-tracing-opentelemetry/src/snapshots/testing_tracing_opentelemetry__filled_http_headers_otel_spans.snap
- testing-tracing-opentelemetry/src/snapshots/testing_tracing_opentelemetry__filled_http_route_for_existing_route.snap
- testing-tracing-opentelemetry/src/snapshots/testing_tracing_opentelemetry__filled_http_route_for_existing_route_otel_spans.snap
- testing-tracing-opentelemetry/src/snapshots/testing_tracing_opentelemetry__status_code_on_close_for_error.snap
- testing-tracing-opentelemetry/src/snapshots/testing_tracing_opentelemetry__status_code_on_close_for_error_otel_spans.snap
- testing-tracing-opentelemetry/src/snapshots/testing_tracing_opentelemetry__status_code_on_close_for_ok.snap
- testing-tracing-opentelemetry/src/snapshots/testing_tracing_opentelemetry__status_code_on_close_for_ok_otel_spans.snap
- testing-tracing-opentelemetry/src/snapshots/testing_tracing_opentelemetry__trace_id_in_child_span.snap
- testing-tracing-opentelemetry/src/snapshots/testing_tracing_opentelemetry__trace_id_in_child_span_for_remote.snap
- testing-tracing-opentelemetry/src/snapshots/testing_tracing_opentelemetry__trace_id_in_child_span_for_remote_otel_spans.snap
- testing-tracing-opentelemetry/src/snapshots/testing_tracing_opentelemetry__trace_id_in_child_span_otel_spans.snap
- tracing-opentelemetry-instrumentation-sdk/src/http/http_server.rs
- tracing-opentelemetry-instrumentation-sdk/src/lib.rs
- tracing-opentelemetry-instrumentation-sdk/src/span_type.rs
**Issue**
- datadog root http span needs to indicate the `span.type` attribute, as [mentioned here](https://github.com/open-telemetry/opentelemetry-rust/blob/ccb510fbd6fdef9694e3b751fd01dbe33c7345c0/opentelemetry-datadog/src/lib.rs#L29-L30) on the opentelemetry_datadog exporter.
- this influences the way datadog APM present some information, like APDEX, that is not available if this fields is not filled with `web`
**Solution**
- default to always inform `span.type` = `web` on `HTTP request` trace
PS: I can make it optional if needed, or based in some config/env var, just let me know!
> feat: add span.type=web on spans

- init-tracing-opentelemetry/Cargo.toml
- init-tracing-opentelemetry/src/otlp.rs
This is intended to allow the use of a gRPC endpoint with tls.  e.g. `OTEL_EXPORTER_OTLP_ENDPOINT=https://example.org:4317`
It is basic such that it allows for connecting to tls endpoint with a valid CA signed cert, but does not enable client cert authentication or certificate pinning.
I was unable to run the tests.
> feat: enable simple basic grpc tls endpoint

- README.md
I wasn't able to get the `axum-otlp` example to connect to Jaeger in when started with version `1.41`, but I could get traces to appear in Jaeger after upgrading.
> Update Jaeger docker tag in README from 1.41 to 1.49

- init-tracing-opentelemetry/src/otlp.rs
- init-tracing-opentelemetry/src/tracing_subscriber_ext.rs
This PR adds support for reading `key1=value1,key2=value2,...` tuples from `OTEL_EXPORTER_OTLP_HEADERS` and `OTEL_EXPORTER_OTLP_TRACES_HEADERS`, thus enabling a smoother quick start from [honeycomb's setup guide](https://docs.honeycomb.io/getting-data-in/opentelemetry-overview/).
> add support for OTLP headers from environment

- axum-tracing-opentelemetry/src/middleware/trace_extractor.rs
- tonic-tracing-opentelemetry/src/middleware/client.rs
- tonic-tracing-opentelemetry/src/middleware/server.rs
See discussion here: https://github.com/rust-lang/rust-clippy/issues/8246
tl;dr: `let _` drops immediately, so for anything that has Guard like behavior, it will not work as expected. `let _enter` will ensure that the guard is dropped at the end of the scope.
> Replace let _ with let _enter

- axum-tracing-opentelemetry/src/middleware/trace_extractor.rs
- tracing-opentelemetry-instrumentation-sdk/src/http/http_server.rs
The old links are not valid anymore. Looks like those specifications were moved out of this repo in https://github.com/open-telemetry/opentelemetry-specification/pull/3711
I added the new ones pinned to the tag to avoid this issue in case it will be changed again.
> Update links to semantic conventions for HTTP spans

- init-tracing-opentelemetry/Cargo.toml
The opentelmetry-otlp package by default loads the opentelemetry-http package in such a way that it does not have an actual http client available, which causes it to error `ExportFailed(NoHttpClient)` on initialization. I added in a link to the `opentelmetry-otlp` `reqwest-client` feature, which will in turn load the `reqwest` crate and link in the `opentelemetry-http` crate's `reqwest` feature.
I'm not 100% this is the best way to do it - the `opentelemetry-otlp` crate has a number of other features allowing for the http client to be activated in other ways. We might want to provide crate consumers more options in how to load it, but I'm not sure what that should look like. On the other hand, if the design intent for this crate is to provide a basic good-enough OpenTelemetry config for …
> Add link to reqwest-client feature

- tracing-opentelemetry-instrumentation-sdk/src/lib.rs
As the TraceContextExt trait cannot be pulled in to a consuming crate, add a helper to this crate to allow the span_id to be retrieved from a OpenTelemetry Context.
> Add a helper to the sdk to retrieve the span_id

- tonic-tracing-opentelemetry/README.md
It currently says "axum-tracing-opentelemetry" which was a little confusing landing on the crates.io page.
> Fix the header of the tonic tracing README.md

- tonic-tracing-opentelemetry/Cargo.toml
Adding the feature to the tonic-tracing-opentelemetry crate as features are not visible across packages - https://doc.rust-lang.org/cargo/reference/features.html#feature-unification
> [Bugfix] Add tracing_level_info feature to tonic-tracing crate

- CHANGELOG.md
- Cargo.toml
- README.md
- init-tracing-opentelemetry/src/otlp.rs
Bumps the version of opentelemetry to use 0.24.
I've only tested the axum middleware which is working end to end
> Update otel libraries to 0.24

- fake-opentelemetry-collector/src/trace.rs
I'm using the `fake-opentelemetry-collector` in some tests and I would like to be able to inspect the contents of events and status. I couldn't see any obvious reasons why these structs field's needed to remain private.
> Make fields of event and status public to make using them in tests easier

- init-tracing-opentelemetry/src/otlp.rs
Starting from tonic 0.12, native TLS root certificates are no longer used by default by tonic exporter (more details here: https://github.com/open-telemetry/opentelemetry-rust/issues/2008#issuecomment-2292294188).
Calling `with_native_roots()` on `ClientTlsConfig` restores the previous behavior.
> use native root tls certificates in tonic exporter

- axum-tracing-opentelemetry/README.md
- examples/axum-otlp/src/main.rs
- examples/grpc/src/client.rs
- examples/grpc/src/server.rs
- examples/load/src/main.rs
- init-tracing-opentelemetry/README.md
- init-tracing-opentelemetry/src/tracing_subscriber_ext.rs
In discussion with the Rust OpenTelemetry crate maintainers, the `shutdown_tracer_provider` function intentionally no longer ensures that the final traces are sent to the OpenTelemetry server before the application exits. To perform this functionality, we now need to call `force_flush` on the TracerProvider instance.
Since the public API functions for the TracerProvider only return a trait object which does not have this function exposed, we need to keep an instance of the actual TracerProvider around. In order to make this simple for consumers of this crate, I have used the guard pattern here so that they do not need to worry about those details or pull in the crates that provide those types. An instance of the TracerProvider is kept in a private field of the TracingGuard struct, which …
> fix: Use guard pattern to allow consumers to ensure final trace is sent

- examples/axum-otlp/src/main.rs
From axum 0.8 release note:
> changing the path parameter syntax from /:single and /*many to
> /{single} and /{*many}
> fix: route in axum example

- init-tracing-opentelemetry/src/error.rs
- init-tracing-opentelemetry/src/tracing_subscriber_ext.rs
- so log's level filter could be defined by parameter (without need to override `RUST_LOG` env variable on caller side
- remove use of `std::env::set_var` (in the lib, and maybe on caller side) that becomes `unsafe` since rust 1.85
> feat: allow to provide log's "directives" via `init_subscribers_and_loglevel`

- init-tracing-opentelemetry/src/tracing_subscriber_ext.rs
> fix: drop on the TracingGuard also shutdown the wrapped TracerProvider

- init-tracing-opentelemetry/Cargo.toml
I was getting in my local and deployed testing:
```
thread 'OpenTelemetry.Traces.BatchProcessor' panicked at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/core/src/ops/function.rs:250:5:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
```
Checking some searches and other Github discussions, I found [this bug](https://github.com/open-telemetry/opentelemetry-rust/issues/2673) which linked [this doc section](https://github.com/open-telemetry/opentelemetry-rust/blob/main/docs/migration_0.28.md#async-runtime-requirements-removed). It seems only the blocking reqwest client is supported by otlp now. This seems to fix it on my local.
> Must use blocking client now

- tonic-tracing-opentelemetry/Cargo.toml
Enabling `tracing_level_info` in `tonic-tracing-opentelemetry` currently does nothing because the feature is actually implemented in `tracing-opentelemetry-instrumentation-sdk`. Fix by making it enable the corresponding feature in the dependency.
> Fix the `tracing_level_info` feature in `tonic-tracing-opentelemetry`
